server:
  port: 8080
  shutdown: graceful
  servlet:
    encoding:
      enabled: true
      force: true

spring:
  web:
    resources:
      add-mappings: false
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100

upload :
  dir : /app/upload

logging:
  level:
    root: info
    org.hibernate.SQL: debug
