server:
  port: ${httpPort}
  shutdown: graceful
  servlet:
    encoding:
      enabled: true
      force: true
      charset: ${file.encoding}

spring:
  web:
    resources:
      add-mappings: false
  datasource:
    url: jdbc:postgresql://localhost:5432/idea
    username: postgres
    password: ${postgres.password}
  #    url: jdbc:h2:tcp://localhost/~/test
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
  data:
    mongodb:
      uri: mongodb://localhost:27017/mgdb

upload :
  dir : C:/DEV/upload
#  dir : /upload

logging:
  level:
    root: info
    org.hibernate.SQL: debug
