server:
  port: ${httpPort}
  shutdown: graceful
  servlet:
    encoding:
      enabled: true
      force: true
      charset: ${file.encoding}

spring:
  web:
    resources:
      add-mappings: false
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
#        show_sql: true
        format_sql: true

upload :
  dir : C:/DEV/upload

logging:
  level:
    root: info
    org.hibernate.SQL: debug
